version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/drunken-wizard/deploy #프로젝트이름

# 추가 설정
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hook:
  Application:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu