version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/drunken-wizard/ #프로젝트이름

# 추가 설정
permissions:
  - object: /home/ubuntu/drunken-wizard/
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root